# Generated by Django 3.2.7 on 2021-09-10 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Identifiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn_13', models.CharField(blank=True, max_length=124, unique=True)),
                ('isbn_10', models.CharField(blank=True, max_length=124, unique=True)),
                ('other', models.CharField(blank=True, max_length=124, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('author', models.CharField(blank=True, max_length=124)),
                ('publshed_date', models.CharField(blank=True, max_length=20)),
                ('page_count', models.IntegerField(blank=True)),
                ('thumbnail', models.URLField(blank=True)),
                ('publication_language', models.CharField(blank=True, max_length=124)),
                ('isbn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books_app.identifiers')),
            ],
        ),
    ]
