# Generated by Django 3.2.7 on 2021-09-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0002_auto_20210911_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=124),
        ),
        migrations.AlterField(
            model_name='book',
            name='page_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_language',
            field=models.CharField(max_length=124),
        ),
    ]
