# Generated by Django 3.2.7 on 2021-09-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0004_auto_20210911_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='thumbnail',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='identifiers',
            name='isbn_10',
            field=models.CharField(max_length=124, null=True),
        ),
        migrations.AlterField(
            model_name='identifiers',
            name='isbn_13',
            field=models.CharField(max_length=124, null=True),
        ),
        migrations.AlterField(
            model_name='identifiers',
            name='other',
            field=models.CharField(max_length=124, null=True),
        ),
    ]
