# Generated by Django 3.2.7 on 2021-09-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0005_auto_20210911_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=124),
        ),
        migrations.DeleteModel(
            name='Identifiers',
        ),
    ]
